# Generated by Django 5.0.3 on 2024-05-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_order_status_remove_payment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
